# Generated by Django 3.1.2 on 2020-10-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category_label', models.CharField(max_length=255)),
                ('products_count', models.IntegerField()),
                ('fetch_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('offer_price', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('total_reviews', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('review_rating', models.FloatField()),
                ('end_date', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('normal_price', models.CharField(max_length=255)),
                ('offer_percent', models.FloatField()),
                ('fetch_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fetch_date', models.DateTimeField()),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='myapi.category')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='myapi.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(through='myapi.Category_product', to='myapi.Product'),
        ),
    ]
