# Generated by Django 3.1.2 on 2020-10-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fetch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category_product',
            name='fetch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fetch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
